export enum ShipmentLegStatus {
  DSTS_NULL,
  DSTS_SL_D_PROCESSING,
  DSTS_SL_D_ASSIGNED_TO_CARRIER,
  DSTS_SL_D_PICKING_UP,
  DSTS_SL_D_IN_TRANSIT,
  DSTS_SL_D_PARTIALLY_DELIVERED,
  DSTS_SL_D_DELIVERED,
  DSTS_SL_D_PARTIALLY_POD,
  DSTS_SL_D_POD,
  DSTS_SL_D_CLOSED,
  DSTS_SL_D_LLPURGED,
}

